language: c
sudo: required

os:
  - linux
  - osx
dist: xenial

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - gawk
      - libssl-dev
      - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake gcc curl gawk python3 || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip3 install ummalqura; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip3 install termcolor; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip3 install wget; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip3 install colorama; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip3 install backports.lzma; fi

script:
  - Tools/build.sh --bloc . --iloc .
  - cd Builds/Debug
  - make test