language: c
sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  - cmake

addons:
  apt:
    packages:
      - gawk
      - php-cli
      - libssl-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake gcc curl gawk php; fi

script:
  - sudo ./Tools/build.sh --bloc .
  - cd /Build/Debug
  - make test