/**
 * @file Core/Data/Ast/List.h
 * Contains the header of class Core::Data::Ast::List.
 *
 * @copyright Copyright (C) 2017 Sarmad Khalid Abdullah
 *
 * @license This file is released under Alusus Public License, Version 1.0.
 * For details on usage and copying conditions read the full license in the
 * accompanying license file or at <http://alusus.net/alusus_license_1_0>.
 */
//==============================================================================

#ifndef CORE_DATA_AST_LIST_H
#define CORE_DATA_AST_LIST_H

namespace Core { namespace Data { namespace Ast
{

/**
 * @brief A generic list to hold parsed data in a PRT.
 * @ingroup data
 *
 * Holds a list in a Parsing Representation Tree (PRT) generated by the generic
 * parsing handler. Any element of this list can be any other TiObject
 * class, enabling the creation of trees needed for holding complete parsed
 * data. This generic list can hold parsed data for any grammar, enabling it and
 * the GenericParsingHandler to be used by default for any grammar production
 * that doesn't have a specific parsing handler. Despite being used by the
 * GenericParsingHandler, this class can be used publicly by any parsing
 * handler.
 */
class List : public SharedList,
             public virtual Bindings, public virtual Metadata, public virtual Clonable, public virtual Printable
{
  //============================================================================
  // Type Info

  TYPE_INFO(List, SharedList, "Core.Data.Ast", "Core", "alusus.net");
  IMPLEMENT_INTERFACES(SharedList, Bindings, Metadata, Clonable, Printable);


  //============================================================================
  // Implementations

  IMPLEMENT_METADATA(List);

  IMPLEMENT_BINDINGS(Bindings,
    (prodId, TiWord, VALUE, setProdId(value), &prodId),
    (sourceLocation, SourceLocation, SHARED_REF, setSourceLocation(value), sourceLocation.get())
  );

  IMPLEMENT_AST_LIST_CLONABLE(List);

  IMPLEMENT_AST_LIST_PRINTABLE(List);


  //============================================================================
  // Constructor / Destructor

  IMPLEMENT_EMPTY_CONSTRUCTOR(List);

  IMPLEMENT_ATTR_CONSTRUCTOR(List);

  IMPLEMENT_ATTR_LIST_CONSTRUCTOR(List);

}; // class

} } } // namespace

#endif
