/**
 * @file Spp/LlvmCodeGen/llvm_code_gen.cpp
 *
 * @copyright Copyright (C) 2026 Sarmad Khalid Abdullah
 *
 * @license This file is released under Alusus Public License, Version 1.0.
 * For details on usage and copying conditions read the full license in the
 * accompanying license file or at <https://alusus.org/license.html>.
 */
//==============================================================================

#include "spp.h"

namespace Spp::LlvmCodeGen
{

void llvmDiagnosticCallback(const llvm::DiagnosticInfo &di, void *context)
{
  std::string msg;
  llvm::raw_string_ostream stream(msg);
  llvm::DiagnosticPrinterRawOStream dpstream(stream);

  di.print(dpstream);
  stream.flush();

  outStream << msg << "\n";
}


void optimizeLlvmModule(llvm::Module &module, llvm::TargetMachine *targetMachine)
{
  if (llvm::verifyModule(module, &llvm::errs())) {
    llvm::errs() << "Invalid IR before optimization\n";
    module.print(llvm::errs(), nullptr);
    llvm::report_fatal_error("Invalid IR generated by TargetGenerator");
  }

  llvm::LoopAnalysisManager lam;
  llvm::FunctionAnalysisManager fam;
  llvm::CGSCCAnalysisManager cgam;
  llvm::ModuleAnalysisManager mam;

  llvm::PassBuilder pb(targetMachine);

  pb.registerModuleAnalyses(mam);
  pb.registerCGSCCAnalyses(cgam);
  pb.registerFunctionAnalyses(fam);
  pb.registerLoopAnalyses(lam);
  pb.crossRegisterProxies(lam, fam, cgam, mam);

  llvm::ModulePassManager mpm = pb.buildPerModuleDefaultPipeline(llvm::OptimizationLevel::O3);
  mpm.addPass(llvm::VerifierPass());

  mpm.run(module, mam);
}

}
