/**
 * @file Core/Data/ParsedList.h
 * Contains the header of class Core::Data::ParsedList.
 *
 * @copyright Copyright (C) 2014 Sarmad Khalid Abdullah
 *
 * @license This file is released under Alusus Public License, Version 1.0.
 * For details on usage and copying conditions read the full license in the
 * accompanying license file or at <http://alusus.net/alusus_license_1_0>.
 */
//==============================================================================

#ifndef DATA_PARSEDLIST_H
#define DATA_PARSEDLIST_H

namespace Core { namespace Data
{

/**
 * @brief A generic list to hold parsed data.
 * @ingroup data
 *
 * This list is used to hold parsed data generated by the generic parsing
 * handler. Any element of this list can be any other IdentifiableObject class,
 * enabling the creation of trees needed for holding complete parsed data. This
 * generic list can hold parsed data for any grammar, enabling it and the
 * GenericParsingHandler to be used by default for any grammar production that
 * doesn't have a specific parsing handler. Despite being used by the
 * GenericParsingHandler, this class can be used publicly by any parsing
 * handler.
 */
class ParsedList : public SharedList,
                   public virtual ParsingMetadataHolder
{
  //============================================================================
  // Type Info

  TYPE_INFO(ParsedList, SharedList, "Core.Data", "Core", "alusus.net");
  IMPLEMENT_INTERFACES_1(SharedList, ParsingMetadataHolder);


  //============================================================================
  // Constructor / Destructor

  public: ParsedList(Word pid=UNKNOWN_ID, Int l=-1, Int c=-1) :
    ParsingMetadataHolder(pid, l, c)
  {
  }

  public: ParsedList(Word pid, const std::initializer_list<SharedPtr<IdentifiableObject>> &args) :
    ParsingMetadataHolder(pid, -1, -1), SharedList(args)
  {
  }

  public: ParsedList(Word pid, Int l, Int c, const std::initializer_list<SharedPtr<IdentifiableObject>> &args) :
    ParsingMetadataHolder(pid, l, c), SharedList(args)
  {
  }

  public: virtual ~ParsedList()
  {
  }

  public: static SharedPtr<ParsedList> create(Word pid=UNKNOWN_ID, Int l=-1, Int c=-1)
  {
    return std::make_shared<ParsedList>(pid, l, c);
  }

  public: static SharedPtr<ParsedList> create(Word pid,
                                              const std::initializer_list<SharedPtr<IdentifiableObject>> &args)
  {
    return std::make_shared<ParsedList>(pid, args);
  }

  public: static SharedPtr<ParsedList> create(Word pid, Int l, Int c,
                                              const std::initializer_list<SharedPtr<IdentifiableObject>> &args)
  {
    return std::make_shared<ParsedList>(pid, l, c, args);
  }


  //============================================================================
  // ParsingMetadataHolder Overrides

  /**
   * @brief Override the original implementation to search the tree if needed.
   * If the value is not yet set for this object and it has children, it will
   * call getLine on the children.
   */
  public: virtual Int getLine() const
  {
    if (ParsingMetadataHolder::getLine() == -1) {
      for (Int i = 0; i < this->getCount(); ++i) {
        ParsingMetadataHolder *ptr = ii_cast<ParsingMetadataHolder>(this->get(i).get());
        if (ptr != 0) {
          Int l = ptr->getLine();
          if (l != -1) return l;
        }
      }
    }
    return ParsingMetadataHolder::getLine();
  }

  /**
   * @brief Override the original implementation to search the tree if needed.
   * If the value is not yet set for this object and it has children, it will
   * call getColumn on the children.
   */
  public: virtual Int getColumn() const
  {
    if (ParsingMetadataHolder::getColumn() == -1) {
      for (Int i = 0; i < this->getCount(); ++i) {
        ParsingMetadataHolder *ptr = ii_cast<ParsingMetadataHolder>(this->get(i).get());
        if (ptr != 0) {
          Int l = ptr->getColumn();
          if (l != -1) return l;
        }
      }
    }
    return ParsingMetadataHolder::getColumn();
  }

  public: virtual IdentifiableObject* getAttribute(Char const *name)
  {
    if (SBSTR(name) == STR("line")) {
      if (ParsingMetadataHolder::getLine() == -1) {
        for (Int i = 0; i < this->getCount(); ++i) {
          ParsingMetadataHolder *ptr = ii_cast<ParsingMetadataHolder>(this->get(i).get());
          if (ptr != 0) {
            if (ptr->getLine() != -1) return ptr->getAttribute(name);
          }
        }
      }
    } else if (SBSTR(name) == STR("column")) {
      if (ParsingMetadataHolder::getColumn() == -1) {
        for (Int i = 0; i < this->getCount(); ++i) {
          ParsingMetadataHolder *ptr = ii_cast<ParsingMetadataHolder>(this->get(i).get());
          if (ptr != 0) {
            if (ptr->getColumn() != -1) return ptr->getAttribute(name);
          }
        }
      }
    }
    return ParsingMetadataHolder::getAttribute(name);
  }

}; // class

} } // namespace

#endif
