/**
 * @file Core/Data/ParsedList.h
 * Contains the header of class Core::Data::ParsedList.
 *
 * @copyright Copyright (C) 2014 Sarmad Khalid Abdullah
 *
 * @license This file is released under Alusus Public License, Version 1.0.
 * For details on usage and copying conditions read the full license in the
 * accompanying license file or at <http://alusus.net/alusus_license_1_0>.
 */
//==============================================================================

#ifndef DATA_PARSEDLIST_H
#define DATA_PARSEDLIST_H

namespace Core { namespace Data
{

/**
 * @brief A generic list to hold parsed data.
 * @ingroup data
 *
 * This list is used to hold parsed data generated by the generic parsing
 * handler. Any element of this list can be any other IdentifiableObject class,
 * enabling the creation of trees needed for holding complete parsed data. This
 * generic list can hold parsed data for any grammar, enabling it and the
 * GenericParsingHandler to be used by default for any grammar production that
 * doesn't have a specific parsing handler. Despite being used by the
 * GenericParsingHandler, this class can be used publicly by any parsing
 * handler.
 */
class ParsedList : public SharedList,
                   public virtual ParsingMetadataHolder
{
  //============================================================================
  // Type Info

  TYPE_INFO(ParsedList, SharedList, "Core.Data", "Core", "alusus.net");
  IMPLEMENT_INTERFACES_1(SharedList, ParsingMetadataHolder);


  //============================================================================
  // Constructor / Destructor

  public: ParsedList()
  {
  }

  public: ParsedList(Word pid, SourceLocation const &sl) :
    ParsingMetadataHolder(pid, sl)
  {
  }

  public: ParsedList(Word pid, const std::initializer_list<SharedPtr<IdentifiableObject>> &args) :
    ParsingMetadataHolder(pid), SharedList(args)
  {
  }

  public: ParsedList(Word pid, SourceLocation const &sl,
                     const std::initializer_list<SharedPtr<IdentifiableObject>> &args) :
    ParsingMetadataHolder(pid, sl), SharedList(args)
  {
  }

  public: virtual ~ParsedList()
  {
  }

  public: static SharedPtr<ParsedList> create()
  {
    return std::make_shared<ParsedList>();
  }

  public: static SharedPtr<ParsedList> create(Word pid, SourceLocation const &sl)
  {
    return std::make_shared<ParsedList>(pid, sl);
  }

  public: static SharedPtr<ParsedList> create(Word pid,
                                              const std::initializer_list<SharedPtr<IdentifiableObject>> &args)
  {
    return std::make_shared<ParsedList>(pid, args);
  }

  public: static SharedPtr<ParsedList> create(Word pid, SourceLocation const &sl,
                                              const std::initializer_list<SharedPtr<IdentifiableObject>> &args)
  {
    return std::make_shared<ParsedList>(pid, sl, args);
  }


  //============================================================================
  // ParsingMetadataHolder Overrides

  /**
   * @brief Override the original implementation to search the tree if needed.
   * If the value is not yet set for this object and it has children, it will
   * call getSourceLocation on the children.
   */
  public: virtual SourceLocation const& getSourceLocation() const
  {
    if (ParsingMetadataHolder::getSourceLocation().line == 0) {
      for (Int i = 0; i < this->getCount(); ++i) {
        ParsingMetadataHolder *ptr = ii_cast<ParsingMetadataHolder>(this->get(i));
        if (ptr != 0) {
          SourceLocation const &sl = ptr->getSourceLocation();
          if (sl.line != 0) return sl;
        }
      }
    }
    return ParsingMetadataHolder::getSourceLocation();
  }

  public: virtual IdentifiableObject* getAttribute(Char const *name)
  {
    if (SBSTR(name) == STR("sourceLocation")) {
      if (ParsingMetadataHolder::getSourceLocation().line == 0) {
        for (Int i = 0; i < this->getCount(); ++i) {
          ParsingMetadataHolder *ptr = ii_cast<ParsingMetadataHolder>(this->get(i));
          if (ptr != 0) {
            if (ptr->getSourceLocation().line != 0) return ptr->getAttribute(name);
          }
        }
      }
    }
    return ParsingMetadataHolder::getAttribute(name);
  }

}; // class

} } // namespace

#endif
