/**
 * @file Core/Data/PrtList.h
 * Contains the header of class Core::Data::PrtList.
 *
 * @copyright Copyright (C) 2015 Sarmad Khalid Abdullah
 *
 * @license This file is released under Alusus Public License, Version 1.0.
 * For details on usage and copying conditions read the full license in the
 * accompanying license file or at <http://alusus.net/alusus_license_1_0>.
 */
//==============================================================================

#ifndef CORE_DATA_PRTLIST_H
#define CORE_DATA_PRTLIST_H

namespace Core { namespace Data
{

/**
 * @brief A generic list to hold parsed data in a PRT.
 * @ingroup data
 *
 * Holds a list in a Parsing Representation Tree (PRT) generated by the generic
 * parsing handler. Any element of this list can be any other IdentifiableObject
 * class, enabling the creation of trees needed for holding complete parsed
 * data. This generic list can hold parsed data for any grammar, enabling it and
 * the GenericParsingHandler to be used by default for any grammar production
 * that doesn't have a specific parsing handler. Despite being used by the
 * GenericParsingHandler, this class can be used publicly by any parsing
 * handler.
 */
class PrtList : public SharedList,
                public virtual ParsingMetadataHolder, public virtual Clonable
{
  //============================================================================
  // Type Info

  TYPE_INFO(PrtList, SharedList, "Core.Data", "Core", "alusus.net");
  IMPLEMENT_INTERFACES_2(SharedList, ParsingMetadataHolder, Clonable);


  //============================================================================
  // Constructor / Destructor

  public: PrtList()
  {
  }

  public: PrtList(Word pid, SourceLocation const &sl) :
    ParsingMetadataHolder(pid, sl)
  {
  }

  public: PrtList(Word pid, const std::initializer_list<SharedPtr<IdentifiableObject>> &args) :
    ParsingMetadataHolder(pid), SharedList(args)
  {
  }

  public: PrtList(Word pid, SourceLocation const &sl,
                     const std::initializer_list<SharedPtr<IdentifiableObject>> &args) :
    ParsingMetadataHolder(pid, sl), SharedList(args)
  {
  }

  public: virtual ~PrtList()
  {
  }

  public: static SharedPtr<PrtList> create()
  {
    return std::make_shared<PrtList>();
  }

  public: static SharedPtr<PrtList> create(Word pid, SourceLocation const &sl)
  {
    return std::make_shared<PrtList>(pid, sl);
  }

  public: static SharedPtr<PrtList> create(Word pid,
                                              const std::initializer_list<SharedPtr<IdentifiableObject>> &args)
  {
    return std::make_shared<PrtList>(pid, args);
  }

  public: static SharedPtr<PrtList> create(Word pid, SourceLocation const &sl,
                                              const std::initializer_list<SharedPtr<IdentifiableObject>> &args)
  {
    return std::make_shared<PrtList>(pid, sl, args);
  }


  //============================================================================
  // ParsingMetadataHolder Overrides

  /**
   * @brief Override the original implementation to search the tree if needed.
   * If the value is not yet set for this object and it has children, it will
   * call getSourceLocation on the children.
   */
  public: virtual SourceLocation const& getSourceLocation() const
  {
    if (ParsingMetadataHolder::getSourceLocation().line == 0) {
      for (Int i = 0; i < this->getCount(); ++i) {
        ParsingMetadataHolder *ptr = ii_cast<ParsingMetadataHolder>(this->get(i));
        if (ptr != 0) {
          SourceLocation const &sl = ptr->getSourceLocation();
          if (sl.line != 0) return sl;
        }
      }
    }
    return ParsingMetadataHolder::getSourceLocation();
  }

  public: virtual IdentifiableObject* getAttribute(Char const *name)
  {
    if (SBSTR(name) == STR("sourceLocation")) {
      if (ParsingMetadataHolder::getSourceLocation().line == 0) {
        for (Int i = 0; i < this->getCount(); ++i) {
          ParsingMetadataHolder *ptr = ii_cast<ParsingMetadataHolder>(this->get(i));
          if (ptr != 0) {
            if (ptr->getSourceLocation().line != 0) return ptr->getAttribute(name);
          }
        }
      }
    }
    return ParsingMetadataHolder::getAttribute(name);
  }


  //============================================================================
  // Clonable Overrides

  public: virtual SharedPtr<IdentifiableObject> clone() const
  {
    SharedPtr<PrtList> newList = std::make_shared<PrtList>();
    newList->setProdId(this->getProdId());
    for (Word i = 0; i < this->getCount(); ++i) {
      newList->add(this->get(i));
    }
    newList->setSourceLocation(this->getSourceLocation());
    return newList;
  }

}; // class

} } // namespace

#endif
