name: macOS 12 X64 - x64-osx

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.0"

      - name: Install dependencies
        run: >
          brew install git ninja python3 ruby &&

          gem install --no-document fpm &&

          curl https://bootstrap.pypa.io/get-pip.py | python3

      - name: Clone and bootstrap vcpkg
        run: >
          git clone https://github.com/microsoft/vcpkg.git "$HOME/vcpkg" &&
          cd "$HOME/vcpkg" &&
          chmod +x bootstrap-vcpkg.sh &&
          ./bootstrap-vcpkg.sh &&
          cd -

      - name: Build Alusus
        run: ALUSUS_VCPKG_REPO_PATH="$HOME/vcpkg" ./Tools/build.sh --clean-and-build --target-triplet x64-osx

      - name: Automated tests Alusus
        run: |
          cd "$(./Tools/build.sh --target-triplet x64-osx --print-build-location)" && ctest --output-on-failure
