name: Ubuntu 22.04 X64 - x64-linux

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: >
          sudo apt-get install -y git cmake libgit2-dev ninja-build build-essential python3 python3-pip ruby rpm &&

          sudo gem install --no-document fpm

      - name: Clone and bootstrap vcpkg
        run: >
          git clone https://github.com/microsoft/vcpkg.git "$HOME/vcpkg" &&
          cd "$HOME/vcpkg" &&
          chmod +x bootstrap-vcpkg.sh &&
          ./bootstrap-vcpkg.sh &&
          cd -

      - name: Build Alusus
        run: ALUSUS_VCPKG_REPO_PATH="$HOME/vcpkg" ./Tools/build.sh --clean-and-build --target-triplet x64-linux

      - name: Automated tests Alusus
        run: |
          cd $(ALUSUS_VCPKG_REPO_PATH="$HOME/vcpkg" ./Tools/build.sh --target-triplet x64-linux --print-build-location) && ctest --output-on-failure
